//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace CombatLog
{
    using System;
    using System.Collections;
    
    
    /// <summary>
    /// Strongly typed collection of CombatLog.HitTypeInfo.
    /// </summary>
    [Serializable()]
    public class HitTypeInfoCollection : System.Collections.CollectionBase
    {
        
        /// <summary>
        /// Default constructor.
        /// </summary>
        public HitTypeInfoCollection() : 
                base()
        {
        }

		public void SortByHitType(System.Windows.Forms.SortOrder Direction)
		{
			this.InnerList.Sort(new Sort.HitTypeInfoCollectionSorter(Direction));
		}
        
        /// <summary>
        /// Gets or sets the value of the CombatLog.HitTypeInfo at a specific position in the HitTypeInfoCollection.
        /// </summary>
        public CombatLog.HitTypeInfo this[int index]
        {
            get
            {
                return ((CombatLog.HitTypeInfo)(this.List[index]));
            }
            set
            {
                this.List[index] = value;
            }
        }

		public CombatLog.HitTypeInfo this[string HitTypeString]
		{
			get
			{
				foreach ( HitTypeInfo h in this.List )
					if ( h.HitTypeString == HitTypeString )
						return h;

				return null;
			}
		}
        
        /// <summary>
        /// Append a CombatLog.HitTypeInfo entry to this collection.
        /// </summary>
        /// <param name="value">CombatLog.HitTypeInfo instance.</param>
        /// <returns>The position into which the new element was inserted.</returns>
        public int Add(CombatLog.HitTypeInfo value)
        {
            return this.List.Add(value);
        }
        
        /// <summary>
        /// Determines whether a specified CombatLog.HitTypeInfo instance is in this collection.
        /// </summary>
        /// <param name="value">CombatLog.HitTypeInfo instance to search for.</param>
        /// <returns>True if the CombatLog.HitTypeInfo instance is in the collection; otherwise false.</returns>
        public bool Contains(CombatLog.HitTypeInfo value)
        {
            return this.List.Contains(value);
        }

		//
		// TODO: Should create a hashtable index on this collection
		//
		public bool Contains(string HitTypeString)
		{
			foreach ( HitTypeInfo h in this.List )
				if ( h.HitTypeString == HitTypeString )
					return true;

			return false;
		}
        
        /// <summary>
        /// Retrieve the index a specified CombatLog.HitTypeInfo instance is in this collection.
        /// </summary>
        /// <param name="value">CombatLog.HitTypeInfo instance to find.</param>
        /// <returns>The zero-based index of the specified CombatLog.HitTypeInfo instance. If the object is not found, the return value is -1.</returns>
        public int IndexOf(CombatLog.HitTypeInfo value)
        {
            return this.List.IndexOf(value);
        }
        
        /// <summary>
        /// Removes a specified CombatLog.HitTypeInfo instance from this collection.
        /// </summary>
        /// <param name="value">The CombatLog.HitTypeInfo instance to remove.</param>
        public void Remove(CombatLog.HitTypeInfo value)
        {
            this.List.Remove(value);
        }
        
        /// <summary>
        /// Returns an enumerator that can iterate through the CombatLog.HitTypeInfo instance.
        /// </summary>
        /// <returns>An CombatLog.HitTypeInfo's enumerator.</returns>
        public new HitTypeInfoCollectionEnumerator GetEnumerator()
        {
            return new HitTypeInfoCollectionEnumerator(this);
        }
        
        /// <summary>
        /// Insert a CombatLog.HitTypeInfo instance into this collection at a specified index.
        /// </summary>
        /// <param name="index">Zero-based index.</param>
        /// <param name="value">The CombatLog.HitTypeInfo instance to insert.</param>
        public void Insert(int index, CombatLog.HitTypeInfo value)
        {
            this.List.Insert(index, value);
        }
        
        /// <summary>
        /// Strongly typed enumerator of CombatLog.HitTypeInfo.
        /// </summary>
        public class HitTypeInfoCollectionEnumerator : object, System.Collections.IEnumerator
        {
            
            /// <summary>
            /// Current index
            /// </summary>
            private int _index;
            
            /// <summary>
            /// Current element pointed to.
            /// </summary>
            private CombatLog.HitTypeInfo _currentElement;
            
            /// <summary>
            /// Collection to enumerate.
            /// </summary>
            private HitTypeInfoCollection _collection;
            
            /// <summary>
            /// Default constructor for enumerator.
            /// </summary>
            /// <param name="collection">Instance of the collection to enumerate.</param>
            internal HitTypeInfoCollectionEnumerator(HitTypeInfoCollection collection)
            {
                _index = -1;
                _collection = collection;
            }
            
            /// <summary>
            /// Gets the CombatLog.HitTypeInfo object in the enumerated HitTypeInfoCollection currently indexed by this instance.
            /// </summary>
            public CombatLog.HitTypeInfo Current
            {
                get
                {
                    if (((_index == -1) 
                                || (_index >= _collection.Count)))
                    {
                        throw new System.IndexOutOfRangeException("Enumerator not started.");
                    }
                    else
                    {
                        return _currentElement;
                    }
                }
            }
            
            /// <summary>
            /// Gets the current element in the collection.
            /// </summary>
            object IEnumerator.Current
            {
                get
                {
                    if (((_index == -1) 
                                || (_index >= _collection.Count)))
                    {
                        throw new System.IndexOutOfRangeException("Enumerator not started.");
                    }
                    else
                    {
                        return _currentElement;
                    }
                }
            }
            
            /// <summary>
            /// Reset the cursor, so it points to the beginning of the enumerator.
            /// </summary>
            public void Reset()
            {
                _index = -1;
                _currentElement = null;
            }
            
            /// <summary>
            /// Advances the enumerator to the next queue of the enumeration, if one is currently available.
            /// </summary>
            /// <returns>true, if the enumerator was succesfully advanced to the next queue; false, if the enumerator has reached the end of the enumeration.</returns>
            public bool MoveNext()
            {
                if ((_index 
                            < (_collection.Count - 1)))
                {
                    _index = (_index + 1);
                    _currentElement = this._collection[_index];
                    return true;
                }
                _index = _collection.Count;
                return false;
            }
        }
    }
}
