//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace CombatLog
{
    using System;
    using System.Collections;
    
    
    /// <summary>
    /// Strongly typed collection of CombatLog.ChartItem.
    /// </summary>
    public class ChartItemCollection : System.Collections.CollectionBase
    {
        
        /// <summary>
        /// Default constructor.
        /// </summary>
        public ChartItemCollection() : 
                base()
        {
        }
        
		public double GetBiggestValue()
		{
			double r = 0;

			foreach ( ChartItem ci in this.List )
			{
				if ( ci.Value > r )
					r = ci.Value;
			}

			return r;
		}

        /// <summary>
        /// Gets or sets the value of the CombatLog.ChartItem at a specific position in the ChartItemCollection.
        /// </summary>
        public CombatLog.ChartItem this[int index]
        {
            get
            {
                return ((CombatLog.ChartItem)(this.List[index]));
            }
            set
            {
                this.List[index] = value;
            }
        }
        
        /// <summary>
        /// Append a CombatLog.ChartItem entry to this collection.
        /// </summary>
        /// <param name="value">CombatLog.ChartItem instance.</param>
        /// <returns>The position into which the new element was inserted.</returns>
        public int Add(CombatLog.ChartItem value)
        {
            return this.List.Add(value);
        }
        
        /// <summary>
        /// Determines whether a specified CombatLog.ChartItem instance is in this collection.
        /// </summary>
        /// <param name="value">CombatLog.ChartItem instance to search for.</param>
        /// <returns>True if the CombatLog.ChartItem instance is in the collection; otherwise false.</returns>
        public bool Contains(CombatLog.ChartItem value)
        {
            return this.List.Contains(value);
        }
        
        /// <summary>
        /// Retrieve the index a specified CombatLog.ChartItem instance is in this collection.
        /// </summary>
        /// <param name="value">CombatLog.ChartItem instance to find.</param>
        /// <returns>The zero-based index of the specified CombatLog.ChartItem instance. If the object is not found, the return value is -1.</returns>
        public int IndexOf(CombatLog.ChartItem value)
        {
            return this.List.IndexOf(value);
        }
        
        /// <summary>
        /// Removes a specified CombatLog.ChartItem instance from this collection.
        /// </summary>
        /// <param name="value">The CombatLog.ChartItem instance to remove.</param>
        public void Remove(CombatLog.ChartItem value)
        {
            this.List.Remove(value);
        }
        
        /// <summary>
        /// Returns an enumerator that can iterate through the CombatLog.ChartItem instance.
        /// </summary>
        /// <returns>An CombatLog.ChartItem's enumerator.</returns>
        public new ChartItemCollectionEnumerator GetEnumerator()
        {
            return new ChartItemCollectionEnumerator(this);
        }
        
        /// <summary>
        /// Insert a CombatLog.ChartItem instance into this collection at a specified index.
        /// </summary>
        /// <param name="index">Zero-based index.</param>
        /// <param name="value">The CombatLog.ChartItem instance to insert.</param>
        public void Insert(int index, CombatLog.ChartItem value)
        {
            this.List.Insert(index, value);
        }
        
        /// <summary>
        /// Strongly typed enumerator of CombatLog.ChartItem.
        /// </summary>
        public class ChartItemCollectionEnumerator : object, System.Collections.IEnumerator
        {
            
            /// <summary>
            /// Current index
            /// </summary>
            private int _index;
            
            /// <summary>
            /// Current element pointed to.
            /// </summary>
            private CombatLog.ChartItem _currentElement;
            
            /// <summary>
            /// Collection to enumerate.
            /// </summary>
            private ChartItemCollection _collection;
            
            /// <summary>
            /// Default constructor for enumerator.
            /// </summary>
            /// <param name="collection">Instance of the collection to enumerate.</param>
            internal ChartItemCollectionEnumerator(ChartItemCollection collection)
            {
                _index = -1;
                _collection = collection;
            }
            
            /// <summary>
            /// Gets the CombatLog.ChartItem object in the enumerated ChartItemCollection currently indexed by this instance.
            /// </summary>
            public CombatLog.ChartItem Current
            {
                get
                {
                    if (((_index == -1) 
                                || (_index >= _collection.Count)))
                    {
                        throw new System.IndexOutOfRangeException("Enumerator not started.");
                    }
                    else
                    {
                        return _currentElement;
                    }
                }
            }
            
            /// <summary>
            /// Gets the current element in the collection.
            /// </summary>
            object IEnumerator.Current
            {
                get
                {
                    if (((_index == -1) 
                                || (_index >= _collection.Count)))
                    {
                        throw new System.IndexOutOfRangeException("Enumerator not started.");
                    }
                    else
                    {
                        return _currentElement;
                    }
                }
            }
            
            /// <summary>
            /// Reset the cursor, so it points to the beginning of the enumerator.
            /// </summary>
            public void Reset()
            {
                _index = -1;
                _currentElement = null;
            }
            
            /// <summary>
            /// Advances the enumerator to the next queue of the enumeration, if one is currently available.
            /// </summary>
            /// <returns>true, if the enumerator was succesfully advanced to the next queue; false, if the enumerator has reached the end of the enumeration.</returns>
            public bool MoveNext()
            {
                if ((_index 
                            < (_collection.Count - 1)))
                {
                    _index = (_index + 1);
                    _currentElement = this._collection[_index];
                    return true;
                }
                _index = _collection.Count;
                return false;
            }
        }
    }
}
