//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace CombatLog
{
    using System;
    using System.Collections;
    
    
    /// <summary>
    /// Strongly typed collection of CombatLog.WeaponSummary.
    /// </summary>
    public class WeaponSummaryCollection : System.Collections.CollectionBase
    {
        
        /// <summary>
        /// Default constructor.
        /// </summary>
        public WeaponSummaryCollection() : 
                base()
        {
        }
        
		public void SortByWeaponName(System.Windows.Forms.SortOrder Direction)
		{
			this.InnerList.Sort(new Sort.WSCByWeaponName(Direction));
		}

        /// <summary>
        /// Gets or sets the value of the CombatLog.WeaponSummary at a specific position in the WeaponSummaryCollection.
        /// </summary>
        public CombatLog.WeaponSummary this[int index]
        {
            get
            {
                return ((CombatLog.WeaponSummary)(this.List[index]));
            }
            set
            {
                this.List[index] = value;
            }
        }
        
        /// <summary>
        /// Append a CombatLog.WeaponSummary entry to this collection.
        /// </summary>
        /// <param name="value">CombatLog.WeaponSummary instance.</param>
        /// <returns>The position into which the new element was inserted.</returns>
        public int Add(CombatLog.WeaponSummary value)
        {
            return this.List.Add(value);
        }
        
        /// <summary>
        /// Determines whether a specified CombatLog.WeaponSummary instance is in this collection.
        /// </summary>
        /// <param name="value">CombatLog.WeaponSummary instance to search for.</param>
        /// <returns>True if the CombatLog.WeaponSummary instance is in the collection; otherwise false.</returns>
        public bool Contains(CombatLog.WeaponSummary value)
        {
            return this.List.Contains(value);
        }
        
        /// <summary>
        /// Retrieve the index a specified CombatLog.WeaponSummary instance is in this collection.
        /// </summary>
        /// <param name="value">CombatLog.WeaponSummary instance to find.</param>
        /// <returns>The zero-based index of the specified CombatLog.WeaponSummary instance. If the object is not found, the return value is -1.</returns>
        public int IndexOf(CombatLog.WeaponSummary value)
        {
            return this.List.IndexOf(value);
        }
        
        /// <summary>
        /// Removes a specified CombatLog.WeaponSummary instance from this collection.
        /// </summary>
        /// <param name="value">The CombatLog.WeaponSummary instance to remove.</param>
        public void Remove(CombatLog.WeaponSummary value)
        {
            this.List.Remove(value);
        }
        
        /// <summary>
        /// Returns an enumerator that can iterate through the CombatLog.WeaponSummary instance.
        /// </summary>
        /// <returns>An CombatLog.WeaponSummary's enumerator.</returns>
        public new WeaponSummaryCollectionEnumerator GetEnumerator()
        {
            return new WeaponSummaryCollectionEnumerator(this);
        }
        
        /// <summary>
        /// Insert a CombatLog.WeaponSummary instance into this collection at a specified index.
        /// </summary>
        /// <param name="index">Zero-based index.</param>
        /// <param name="value">The CombatLog.WeaponSummary instance to insert.</param>
        public void Insert(int index, CombatLog.WeaponSummary value)
        {
            this.List.Insert(index, value);
        }
        
        /// <summary>
        /// Strongly typed enumerator of CombatLog.WeaponSummary.
        /// </summary>
        public class WeaponSummaryCollectionEnumerator : object, System.Collections.IEnumerator
        {
            
            /// <summary>
            /// Current index
            /// </summary>
            private int _index;
            
            /// <summary>
            /// Current element pointed to.
            /// </summary>
            private CombatLog.WeaponSummary _currentElement;
            
            /// <summary>
            /// Collection to enumerate.
            /// </summary>
            private WeaponSummaryCollection _collection;
            
            /// <summary>
            /// Default constructor for enumerator.
            /// </summary>
            /// <param name="collection">Instance of the collection to enumerate.</param>
            internal WeaponSummaryCollectionEnumerator(WeaponSummaryCollection collection)
            {
                _index = -1;
                _collection = collection;
            }
            
            /// <summary>
            /// Gets the CombatLog.WeaponSummary object in the enumerated WeaponSummaryCollection currently indexed by this instance.
            /// </summary>
            public CombatLog.WeaponSummary Current
            {
                get
                {
                    if (((_index == -1) 
                                || (_index >= _collection.Count)))
                    {
                        throw new System.IndexOutOfRangeException("Enumerator not started.");
                    }
                    else
                    {
                        return _currentElement;
                    }
                }
            }
            
            /// <summary>
            /// Gets the current element in the collection.
            /// </summary>
            object IEnumerator.Current
            {
                get
                {
                    if (((_index == -1) 
                                || (_index >= _collection.Count)))
                    {
                        throw new System.IndexOutOfRangeException("Enumerator not started.");
                    }
                    else
                    {
                        return _currentElement;
                    }
                }
            }
            
            /// <summary>
            /// Reset the cursor, so it points to the beginning of the enumerator.
            /// </summary>
            public void Reset()
            {
                _index = -1;
                _currentElement = null;
            }
            
            /// <summary>
            /// Advances the enumerator to the next queue of the enumeration, if one is currently available.
            /// </summary>
            /// <returns>true, if the enumerator was succesfully advanced to the next queue; false, if the enumerator has reached the end of the enumeration.</returns>
            public bool MoveNext()
            {
                if ((_index 
                            < (_collection.Count - 1)))
                {
                    _index = (_index + 1);
                    _currentElement = this._collection[_index];
                    return true;
                }
                _index = _collection.Count;
                return false;
            }
        }
    }
}
