//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace CombatLog.Config
{
    using System;
    using System.Collections;
    
    
    /// <summary>
    /// Strongly typed collection of CombatLog.Config.WBColumns.
    /// </summary>
    public class WBColumnsCollection : System.Collections.CollectionBase
    {
		private Hashtable _ColumnIndex = new Hashtable();

        /// <summary>
        /// Default constructor.
        /// </summary>
        public WBColumnsCollection() : 
                base()
        {
        }

		private void IndexThis(WBColumns value)
		{
			if ( _ColumnIndex == null )
				_ColumnIndex = new Hashtable();

			if ( !_ColumnIndex.ContainsKey(value.AttributeName) )
				_ColumnIndex.Add(value.AttributeName, value);
		}

		public CombatLog.Config.WBColumns this[string AttributeName]
		{
			get { return (WBColumns)_ColumnIndex[AttributeName]; }
		}

        /// <summary>
        /// Gets or sets the value of the CombatLog.Config.WBColumns at a specific position in the WBColumnsCollection.
        /// </summary>
        public CombatLog.Config.WBColumns this[int index]
        {
            get
            {
                return ((CombatLog.Config.WBColumns)(this.List[index]));
            }
            set
            {
                this.List[index] = value;
            }
        }
        
        /// <summary>
        /// Append a CombatLog.Config.WBColumns entry to this collection.
        /// </summary>
        /// <param name="value">CombatLog.Config.WBColumns instance.</param>
        /// <returns>The position into which the new element was inserted.</returns>
        public int Add(CombatLog.Config.WBColumns value)
        {
			IndexThis(value);
            return this.List.Add(value);
        }
        
        /// <summary>
        /// Determines whether a specified CombatLog.Config.WBColumns instance is in this collection.
        /// </summary>
        /// <param name="value">CombatLog.Config.WBColumns instance to search for.</param>
        /// <returns>True if the CombatLog.Config.WBColumns instance is in the collection; otherwise false.</returns>
        public bool Contains(CombatLog.Config.WBColumns value)
        {
            return this.List.Contains(value);
        }
        
        /// <summary>
        /// Retrieve the index a specified CombatLog.Config.WBColumns instance is in this collection.
        /// </summary>
        /// <param name="value">CombatLog.Config.WBColumns instance to find.</param>
        /// <returns>The zero-based index of the specified CombatLog.Config.WBColumns instance. If the object is not found, the return value is -1.</returns>
        public int IndexOf(CombatLog.Config.WBColumns value)
        {
            return this.List.IndexOf(value);
        }
        
        /// <summary>
        /// Removes a specified CombatLog.Config.WBColumns instance from this collection.
        /// </summary>
        /// <param name="value">The CombatLog.Config.WBColumns instance to remove.</param>
        public void Remove(CombatLog.Config.WBColumns value)
        {
            this.List.Remove(value);
        }
        
        /// <summary>
        /// Returns an enumerator that can iterate through the CombatLog.Config.WBColumns instance.
        /// </summary>
        /// <returns>An CombatLog.Config.WBColumns's enumerator.</returns>
        public new WBColumnsCollectionEnumerator GetEnumerator()
        {
            return new WBColumnsCollectionEnumerator(this);
        }
        
        /// <summary>
        /// Insert a CombatLog.Config.WBColumns instance into this collection at a specified index.
        /// </summary>
        /// <param name="index">Zero-based index.</param>
        /// <param name="value">The CombatLog.Config.WBColumns instance to insert.</param>
        public void Insert(int index, CombatLog.Config.WBColumns value)
        {
            this.List.Insert(index, value);
        }
        
        /// <summary>
        /// Strongly typed enumerator of CombatLog.Config.WBColumns.
        /// </summary>
        public class WBColumnsCollectionEnumerator : object, System.Collections.IEnumerator
        {
            
            /// <summary>
            /// Current index
            /// </summary>
            private int _index;
            
            /// <summary>
            /// Current element pointed to.
            /// </summary>
            private CombatLog.Config.WBColumns _currentElement;
            
            /// <summary>
            /// Collection to enumerate.
            /// </summary>
            private WBColumnsCollection _collection;
            
            /// <summary>
            /// Default constructor for enumerator.
            /// </summary>
            /// <param name="collection">Instance of the collection to enumerate.</param>
            internal WBColumnsCollectionEnumerator(WBColumnsCollection collection)
            {
                _index = -1;
                _collection = collection;
            }
            
            /// <summary>
            /// Gets the CombatLog.Config.WBColumns object in the enumerated WBColumnsCollection currently indexed by this instance.
            /// </summary>
            public CombatLog.Config.WBColumns Current
            {
                get
                {
                    if (((_index == -1) 
                                || (_index >= _collection.Count)))
                    {
                        throw new System.IndexOutOfRangeException("Enumerator not started.");
                    }
                    else
                    {
                        return _currentElement;
                    }
                }
            }
            
            /// <summary>
            /// Gets the current element in the collection.
            /// </summary>
            object IEnumerator.Current
            {
                get
                {
                    if (((_index == -1) 
                                || (_index >= _collection.Count)))
                    {
                        throw new System.IndexOutOfRangeException("Enumerator not started.");
                    }
                    else
                    {
                        return _currentElement;
                    }
                }
            }
            
            /// <summary>
            /// Reset the cursor, so it points to the beginning of the enumerator.
            /// </summary>
            public void Reset()
            {
                _index = -1;
                _currentElement = null;
            }
            
            /// <summary>
            /// Advances the enumerator to the next queue of the enumeration, if one is currently available.
            /// </summary>
            /// <returns>true, if the enumerator was succesfully advanced to the next queue; false, if the enumerator has reached the end of the enumeration.</returns>
            public bool MoveNext()
            {
                if ((_index 
                            < (_collection.Count - 1)))
                {
                    _index = (_index + 1);
                    _currentElement = this._collection[_index];
                    return true;
                }
                _index = _collection.Count;
                return false;
            }
        }
    }
}
