//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace CombatLog.VersionManager
{
    using System;
	using System.IO;
	using System.Diagnostics;
	using System.Xml.Serialization;
    using System.Collections;
    
    
    /// <summary>
    /// Strongly typed collection of CombatLog.VersionManager.VersionInfo.
    /// </summary>
    public class VersionInfoCollection : System.Collections.CollectionBase
    {
        
        /// <summary>
        /// Default constructor.
        /// </summary>
        public VersionInfoCollection() : 
                base()
        {
        }
        
        /// <summary>
        /// Gets or sets the value of the CombatLog.VersionManager.VersionInfo at a specific position in the VersionInfoCollection.
        /// </summary>
        public CombatLog.VersionManager.VersionInfo this[int index]
        {
            get
            {
                return ((CombatLog.VersionManager.VersionInfo)(this.List[index]));
            }
            set
            {
                this.List[index] = value;
            }
        }
        
        /// <summary>
        /// Append a CombatLog.VersionManager.VersionInfo entry to this collection.
        /// </summary>
        /// <param name="value">CombatLog.VersionManager.VersionInfo instance.</param>
        /// <returns>The position into which the new element was inserted.</returns>
        public int Add(CombatLog.VersionManager.VersionInfo value)
        {
            return this.List.Add(value);
        }
        
        /// <summary>
        /// Determines whether a specified CombatLog.VersionManager.VersionInfo instance is in this collection.
        /// </summary>
        /// <param name="value">CombatLog.VersionManager.VersionInfo instance to search for.</param>
        /// <returns>True if the CombatLog.VersionManager.VersionInfo instance is in the collection; otherwise false.</returns>
        public bool Contains(CombatLog.VersionManager.VersionInfo value)
        {
            return this.List.Contains(value);
        }
        
        /// <summary>
        /// Retrieve the index a specified CombatLog.VersionManager.VersionInfo instance is in this collection.
        /// </summary>
        /// <param name="value">CombatLog.VersionManager.VersionInfo instance to find.</param>
        /// <returns>The zero-based index of the specified CombatLog.VersionManager.VersionInfo instance. If the object is not found, the return value is -1.</returns>
        public int IndexOf(CombatLog.VersionManager.VersionInfo value)
        {
            return this.List.IndexOf(value);
        }
        
        /// <summary>
        /// Removes a specified CombatLog.VersionManager.VersionInfo instance from this collection.
        /// </summary>
        /// <param name="value">The CombatLog.VersionManager.VersionInfo instance to remove.</param>
        public void Remove(CombatLog.VersionManager.VersionInfo value)
        {
            this.List.Remove(value);
        }
        
        /// <summary>
        /// Returns an enumerator that can iterate through the CombatLog.VersionManager.VersionInfo instance.
        /// </summary>
        /// <returns>An CombatLog.VersionManager.VersionInfo's enumerator.</returns>
        public new VersionInfoCollectionEnumerator GetEnumerator()
        {
            return new VersionInfoCollectionEnumerator(this);
        }
        
        /// <summary>
        /// Insert a CombatLog.VersionManager.VersionInfo instance into this collection at a specified index.
        /// </summary>
        /// <param name="index">Zero-based index.</param>
        /// <param name="value">The CombatLog.VersionManager.VersionInfo instance to insert.</param>
        public void Insert(int index, CombatLog.VersionManager.VersionInfo value)
        {
            this.List.Insert(index, value);
        }
        
        /// <summary>
        /// Strongly typed enumerator of CombatLog.VersionManager.VersionInfo.
        /// </summary>
        public class VersionInfoCollectionEnumerator : object, System.Collections.IEnumerator
        {
            
            /// <summary>
            /// Current index
            /// </summary>
            private int _index;
            
            /// <summary>
            /// Current element pointed to.
            /// </summary>
            private CombatLog.VersionManager.VersionInfo _currentElement;
            
            /// <summary>
            /// Collection to enumerate.
            /// </summary>
            private VersionInfoCollection _collection;
            
            /// <summary>
            /// Default constructor for enumerator.
            /// </summary>
            /// <param name="collection">Instance of the collection to enumerate.</param>
            internal VersionInfoCollectionEnumerator(VersionInfoCollection collection)
            {
                _index = -1;
                _collection = collection;
            }
            
            /// <summary>
            /// Gets the CombatLog.VersionManager.VersionInfo object in the enumerated VersionInfoCollection currently indexed by this instance.
            /// </summary>
            public CombatLog.VersionManager.VersionInfo Current
            {
                get
                {
                    if (((_index == -1) 
                                || (_index >= _collection.Count)))
                    {
                        throw new System.IndexOutOfRangeException("Enumerator not started.");
                    }
                    else
                    {
                        return _currentElement;
                    }
                }
            }
            
            /// <summary>
            /// Gets the current element in the collection.
            /// </summary>
            object IEnumerator.Current
            {
                get
                {
                    if (((_index == -1) 
                                || (_index >= _collection.Count)))
                    {
                        throw new System.IndexOutOfRangeException("Enumerator not started.");
                    }
                    else
                    {
                        return _currentElement;
                    }
                }
            }
            
            /// <summary>
            /// Reset the cursor, so it points to the beginning of the enumerator.
            /// </summary>
            public void Reset()
            {
                _index = -1;
                _currentElement = null;
            }
            
            /// <summary>
            /// Advances the enumerator to the next queue of the enumeration, if one is currently available.
            /// </summary>
            /// <returns>true, if the enumerator was succesfully advanced to the next queue; false, if the enumerator has reached the end of the enumeration.</returns>
            public bool MoveNext()
            {
                if ((_index 
                            < (_collection.Count - 1)))
                {
                    _index = (_index + 1);
                    _currentElement = this._collection[_index];
                    return true;
                }
                _index = _collection.Count;
                return false;
            }
        }
    }
}
